flags: {}
packages:
- '.'
- '../ghcjs-dom'
extra-deps:
- ghcjs-dom-0.2.2.0
- AC-Vector-2.3.2
- data-default-0.5.3
- lens-4.13.2.1
- base-orphans-0.5.3
- bifunctors-5.2.1
- comonad-5
- contravariant-1.4
- data-default-class-0.0.1
- data-default-instances-base-0.0.1
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- distributive-0.5.0.2
- exceptions-0.8.2.1
- free-4.12.4
- kan-extensions-5.0.1
- profunctors-5.2
- reflection-2.1.2
- semigroupoids-5.0.1
- semigroups-0.18.1
- tagged-0.8.3
- transformers-compat-0.5.1.4
- void-0.7.1
- StateVar-1.1.0.3
- adjunctions-4.3
- prelude-extras-0.4.0.3
resolver: ghcjs-0.2.0_ghc-7.10.2
